language: php
php:
  - '7.1'

services:
  - mysql

install:
  - composer install
  - php bin/console doctrine:database:create --env=test
  - php bin/console doctrine:schema:update --force --env=test
  - php bin/console doctrine:fixtures:load -n --env=test

script:
   - vendor/bin/simple-phpunit

branches:
  only:
  - feature/improvement_role
  - feature/code_coverage

before-install:
  - composer self-update